/** Static list of the 114 surahs, so every one of them is searchable offline. */
export type SurahName = { n: number; name: string; arabic: string; meaning: string };

export const SURAH_NAMES: SurahName[] = [
  { n: 1, name: "Al-Fatihah", arabic: "الفاتحة", meaning: "The Opening" },
  { n: 2, name: "Al-Baqarah", arabic: "البقرة", meaning: "The Cow" },
  { n: 3, name: "Ali 'Imran", arabic: "آل عمران", meaning: "Family of Imran" },
  { n: 4, name: "An-Nisa", arabic: "النساء", meaning: "The Women" },
  { n: 5, name: "Al-Ma'idah", arabic: "المائدة", meaning: "The Table Spread" },
  { n: 6, name: "Al-An'am", arabic: "الأنعام", meaning: "The Cattle" },
  { n: 7, name: "Al-A'raf", arabic: "الأعراف", meaning: "The Heights" },
  { n: 8, name: "Al-Anfal", arabic: "الأنفال", meaning: "The Spoils of War" },
  { n: 9, name: "At-Tawbah", arabic: "التوبة", meaning: "The Repentance" },
  { n: 10, name: "Yunus", arabic: "يونس", meaning: "Jonah" },
  { n: 11, name: "Hud", arabic: "هود", meaning: "Hud" },
  { n: 12, name: "Yusuf", arabic: "يوسف", meaning: "Joseph" },
  { n: 13, name: "Ar-Ra'd", arabic: "الرعد", meaning: "The Thunder" },
  { n: 14, name: "Ibrahim", arabic: "إبراهيم", meaning: "Abraham" },
  { n: 15, name: "Al-Hijr", arabic: "الحجر", meaning: "The Rocky Tract" },
  { n: 16, name: "An-Nahl", arabic: "النحل", meaning: "The Bee" },
  { n: 17, name: "Al-Isra", arabic: "الإسراء", meaning: "The Night Journey" },
  { n: 18, name: "Al-Kahf", arabic: "الكهف", meaning: "The Cave" },
  { n: 19, name: "Maryam", arabic: "مريم", meaning: "Mary" },
  { n: 20, name: "Ta-Ha", arabic: "طه", meaning: "Ta-Ha" },
  { n: 21, name: "Al-Anbya", arabic: "الأنبياء", meaning: "The Prophets" },
  { n: 22, name: "Al-Hajj", arabic: "الحج", meaning: "The Pilgrimage" },
  { n: 23, name: "Al-Mu'minun", arabic: "المؤمنون", meaning: "The Believers" },
  { n: 24, name: "An-Nur", arabic: "النور", meaning: "The Light" },
  { n: 25, name: "Al-Furqan", arabic: "الفرقان", meaning: "The Criterion" },
  { n: 26, name: "Ash-Shu'ara", arabic: "الشعراء", meaning: "The Poets" },
  { n: 27, name: "An-Naml", arabic: "النمل", meaning: "The Ant" },
  { n: 28, name: "Al-Qasas", arabic: "القصص", meaning: "The Stories" },
  { n: 29, name: "Al-'Ankabut", arabic: "العنكبوت", meaning: "The Spider" },
  { n: 30, name: "Ar-Rum", arabic: "الروم", meaning: "The Romans" },
  { n: 31, name: "Luqman", arabic: "لقمان", meaning: "Luqman" },
  { n: 32, name: "As-Sajdah", arabic: "السجدة", meaning: "The Prostration" },
  { n: 33, name: "Al-Ahzab", arabic: "الأحزاب", meaning: "The Combined Forces" },
  { n: 34, name: "Saba", arabic: "سبأ", meaning: "Sheba" },
  { n: 35, name: "Fatir", arabic: "فاطر", meaning: "Originator" },
  { n: 36, name: "Ya-Sin", arabic: "يس", meaning: "Ya Sin" },
  { n: 37, name: "As-Saffat", arabic: "الصافات", meaning: "Those Who Set The Ranks" },
  { n: 38, name: "Sad", arabic: "ص", meaning: "The Letter Sad" },
  { n: 39, name: "Az-Zumar", arabic: "الزمر", meaning: "The Troops" },
  { n: 40, name: "Ghafir", arabic: "غافر", meaning: "The Forgiver" },
  { n: 41, name: "Fussilat", arabic: "فصلت", meaning: "Explained in Detail" },
  { n: 42, name: "Ash-Shura", arabic: "الشورى", meaning: "The Consultation" },
  { n: 43, name: "Az-Zukhruf", arabic: "الزخرف", meaning: "The Ornaments of Gold" },
  { n: 44, name: "Ad-Dukhan", arabic: "الدخان", meaning: "The Smoke" },
  { n: 45, name: "Al-Jathiyah", arabic: "الجاثية", meaning: "The Crouching" },
  { n: 46, name: "Al-Ahqaf", arabic: "الأحقاف", meaning: "The Wind-Curved Sandhills" },
  { n: 47, name: "Muhammad", arabic: "محمد", meaning: "Muhammad" },
  { n: 48, name: "Al-Fath", arabic: "الفتح", meaning: "The Victory" },
  { n: 49, name: "Al-Hujurat", arabic: "الحجرات", meaning: "The Rooms" },
  { n: 50, name: "Qaf", arabic: "ق", meaning: "The Letter Qaf" },
  { n: 51, name: "Adh-Dhariyat", arabic: "الذاريات", meaning: "The Winnowing Winds" },
  { n: 52, name: "At-Tur", arabic: "الطور", meaning: "The Mount" },
  { n: 53, name: "An-Najm", arabic: "النجم", meaning: "The Star" },
  { n: 54, name: "Al-Qamar", arabic: "القمر", meaning: "The Moon" },
  { n: 55, name: "Ar-Rahman", arabic: "الرحمن", meaning: "The Beneficent" },
  { n: 56, name: "Al-Waqi'ah", arabic: "الواقعة", meaning: "The Inevitable" },
  { n: 57, name: "Al-Hadid", arabic: "الحديد", meaning: "The Iron" },
  { n: 58, name: "Al-Mujadila", arabic: "المجادلة", meaning: "The Pleading Woman" },
  { n: 59, name: "Al-Hashr", arabic: "الحشر", meaning: "The Exile" },
  { n: 60, name: "Al-Mumtahanah", arabic: "الممتحنة", meaning: "She That Is To Be Examined" },
  { n: 61, name: "As-Saff", arabic: "الصف", meaning: "The Ranks" },
  { n: 62, name: "Al-Jumu'ah", arabic: "الجمعة", meaning: "The Congregation, Friday" },
  { n: 63, name: "Al-Munafiqun", arabic: "المنافقون", meaning: "The Hypocrites" },
  { n: 64, name: "At-Taghabun", arabic: "التغابن", meaning: "The Mutual Disillusion" },
  { n: 65, name: "At-Talaq", arabic: "الطلاق", meaning: "The Divorce" },
  { n: 66, name: "At-Tahrim", arabic: "التحريم", meaning: "The Prohibition" },
  { n: 67, name: "Al-Mulk", arabic: "الملك", meaning: "The Sovereignty" },
  { n: 68, name: "Al-Qalam", arabic: "القلم", meaning: "The Pen" },
  { n: 69, name: "Al-Haqqah", arabic: "الحاقة", meaning: "The Reality" },
  { n: 70, name: "Al-Ma'arij", arabic: "المعارج", meaning: "The Ascending Stairways" },
  { n: 71, name: "Nuh", arabic: "نوح", meaning: "Noah" },
  { n: 72, name: "Al-Jinn", arabic: "الجن", meaning: "The Jinn" },
  { n: 73, name: "Al-Muzzammil", arabic: "المزمل", meaning: "The Enshrouded One" },
  { n: 74, name: "Al-Muddaththir", arabic: "المدثر", meaning: "The Cloaked One" },
  { n: 75, name: "Al-Qiyamah", arabic: "القيامة", meaning: "The Resurrection" },
  { n: 76, name: "Al-Insan", arabic: "الإنسان", meaning: "Man" },
  { n: 77, name: "Al-Mursalat", arabic: "المرسلات", meaning: "The Emissaries" },
  { n: 78, name: "An-Naba", arabic: "النبأ", meaning: "The Tidings" },
  { n: 79, name: "An-Nazi'at", arabic: "النازعات", meaning: "Those Who Drag Forth" },
  { n: 80, name: "'Abasa", arabic: "عبس", meaning: "He Frowned" },
  { n: 81, name: "At-Takwir", arabic: "التكوير", meaning: "The Overthrowing" },
  { n: 82, name: "Al-Infitar", arabic: "الانفطار", meaning: "The Cleaving" },
  { n: 83, name: "Al-Mutaffifin", arabic: "المطففين", meaning: "The Defrauding" },
  { n: 84, name: "Al-Inshiqaq", arabic: "الانشقاق", meaning: "The Sundering" },
  { n: 85, name: "Al-Buruj", arabic: "البروج", meaning: "The Mansions of the Stars" },
  { n: 86, name: "At-Tariq", arabic: "الطارق", meaning: "The Nightcomer" },
  { n: 87, name: "Al-A'la", arabic: "الأعلى", meaning: "The Most High" },
  { n: 88, name: "Al-Ghashiyah", arabic: "الغاشية", meaning: "The Overwhelming" },
  { n: 89, name: "Al-Fajr", arabic: "الفجر", meaning: "The Dawn" },
  { n: 90, name: "Al-Balad", arabic: "البلد", meaning: "The City" },
  { n: 91, name: "Ash-Shams", arabic: "الشمس", meaning: "The Sun" },
  { n: 92, name: "Al-Layl", arabic: "الليل", meaning: "The Night" },
  { n: 93, name: "Ad-Duha", arabic: "الضحى", meaning: "The Morning Hours" },
  { n: 94, name: "Ash-Sharh", arabic: "الشرح", meaning: "The Relief" },
  { n: 95, name: "At-Tin", arabic: "التين", meaning: "The Fig" },
  { n: 96, name: "Al-'Alaq", arabic: "العلق", meaning: "The Clot" },
  { n: 97, name: "Al-Qadr", arabic: "القدر", meaning: "The Power" },
  { n: 98, name: "Al-Bayyinah", arabic: "البينة", meaning: "The Clear Proof" },
  { n: 99, name: "Az-Zalzalah", arabic: "الزلزلة", meaning: "The Earthquake" },
  { n: 100, name: "Al-'Adiyat", arabic: "العاديات", meaning: "The Courser" },
  { n: 101, name: "Al-Qari'ah", arabic: "القارعة", meaning: "The Calamity" },
  { n: 102, name: "At-Takathur", arabic: "التكاثر", meaning: "The Rivalry in World Increase" },
  { n: 103, name: "Al-'Asr", arabic: "العصر", meaning: "The Declining Day" },
  { n: 104, name: "Al-Humazah", arabic: "الهمزة", meaning: "The Traducer" },
  { n: 105, name: "Al-Fil", arabic: "الفيل", meaning: "The Elephant" },
  { n: 106, name: "Quraysh", arabic: "قريش", meaning: "Quraysh" },
  { n: 107, name: "Al-Ma'un", arabic: "الماعون", meaning: "The Small Kindnesses" },
  { n: 108, name: "Al-Kawthar", arabic: "الكوثر", meaning: "The Abundance" },
  { n: 109, name: "Al-Kafirun", arabic: "الكافرون", meaning: "The Disbelievers" },
  { n: 110, name: "An-Nasr", arabic: "النصر", meaning: "The Divine Support" },
  { n: 111, name: "Al-Masad", arabic: "المسد", meaning: "The Palm Fibre" },
  { n: 112, name: "Al-Ikhlas", arabic: "الإخلاص", meaning: "The Sincerity" },
  { n: 113, name: "Al-Falaq", arabic: "الفلق", meaning: "The Daybreak" },
  { n: 114, name: "An-Nas", arabic: "الناس", meaning: "Mankind" },
];
